figure;
subplot(7,3,1);
image(imgs{20});
axis square; axis off;
subplot(7,3,2);
image(imgs{10});
axis square; axis off;
subplot(7,3,3);
image(imgs{11});
axis square; axis off;
subplot(7,3,4);
image(imgs{1});
axis square; axis off;
subplot(7,3,5);
image(imgs{2});
axis square; axis off;
subplot(7,3,6);
image(imgs{3});
axis square; axis off;
subplot(7,3,7);
image(imgs{6});
axis square; axis off;
subplot(7,3,8);
image(imgs{5});
axis square; axis off;
subplot(7,3,9);
image(imgs{4});
axis square; axis off;
subplot(7,3,10);
image(imgs{7});
axis square; axis off;
subplot(7,3,11);
image(imgs{13});
axis square; axis off;
subplot(7,3,12);
image(imgs{12});
axis square; axis off;
subplot(7,3,13);
image(imgs{8});
axis square; axis off;
subplot(7,3,14);
image(imgs{4});
axis square; axis off;
subplot(7,3,15);
image(imgs{19});
axis square; axis off;
subplot(7,3,16);
image(imgs{9});
axis square; axis off;
subplot(7,3,17);
image(imgs{15});
axis square; axis off;
subplot(7,3,18);
image(imgs{18});
axis square; axis off;

subplot(7,3,20);
image(imgs{16});
axis square; axis off;
subplot(7,3,21);
image(imgs{17});
axis square; axis off;
